### ISSUE TITLE
Top shelf movie posters need to be bigger

### ISSUE THREAD

**Issue by steverae68** [fastcolors/skin.sio2#19]

**Comment by steverae68** [comment]
Hi, looking at the poster artwork that is displayed in the top shelf, this needs to be bigger as In pineapple.tv or tvOS-x

**Comment by fastcolors** [comment]
I made an exact replica of ATV4 shelf, i took a screenshot of the ATV4 actual homepage with movies on shelf, and made it a background for the skin, then I adjusted the size to match original one... I could make them bigger but right now they are exactly as the apple ones (slightly shorter since i use the keep aspectratio, and apparently apple covers are longer then fanart.tv ones.. ;) )

check this out:

<img width="500" alt="test_over" src="https://cloud.githubusercontent.com/assets/2766945/21727946/04040eb6-d444-11e6-971c-9be19d50211d.png">

should I go for stretch and fill the missing pixels?

**Comment by fastcolors** [comment]
<img width="500" alt="fix" src="https://cloud.githubusercontent.com/assets/2766945/21728493/c7d6cdcc-d446-11e6-8fc4-93a177a51000.png">

if this is good i'll close this. :-)

**Comment by fastcolors** [comment]
actually... I just took a screenshot off tvOS 10.1 and posters are way smaller!!!

check THIS one out!!! (screenshot from ATV off Xcode i took myself)

<img width="500" alt="error" src="https://cloud.githubusercontent.com/assets/2766945/21729689/70e4112c-d44c-11e6-8aac-5dba98277494.png">

**Comment by fastcolors** [comment]
I also noticed font under icon needs to be bigger

**Comment by steverae68** [comment]
Posters are looking great now for movies in your library.  However, for some reason TV shows does not show anything on top shelf

**Comment by fastcolors** [comment]
do you have any playing show? if the skin is on recommended, it only shows stuff if you have unwatched episodes of a show and you watched some.

for example play the first episode of a new show then the next episodes will show up

i switched the order of episodes so it should now have default to recently added episodes...

closing this, If tv shows not working yet let me know
