### ISSUE TITLE
low res (1280x1024) issue with topshelf poster view for movies

### ISSUE THREAD

**Issue by steverae68** [fastcolors/skin.sio2#35]
Hi

My second display on my iMac (Pioneer 50" Kuro series 9) for some reason runs at 1280x1080 res, not an issue as it's used for kodi display, however, when i select movie posters they shrink at this res.

This can be seen by selecting this res within kodi video display settings too.  works find on my iMac screen at 2560x1440 (iMac 27" i7)  

![screen shot 2017-01-09 at 12 03 56](https://cloud.githubusercontent.com/assets/17755581/21766070/473239ac-d664-11e6-89f2-3dea36cc3fff.png)

Here is a picture showing what i mean, when you move left to right, instead of the poster growing slightly, they shrink like the first poster shown above

**Comment by fastcolors** [comment]
fixed!

**Comment by steverae68** [comment]
now, all the tp shelf movie posters start the same size as in the above pic of spectral... really squashed.  :(

**Comment by fastcolors** [comment]
Nope, spectral is the correct one! All the others are streched! Now usino the keep aspectratio to show the correct size

**Comment by fastcolors** [comment]
I do understand what you mean, by unfortunately the skin only supports 1920x1080 and changes layout if one dimension changes, that cannot be corrected unless another resolution file is made... and that isn't happening 😉 Because it would mean writing an all new set of the skin xmls. Estuary is done like that, but I don't have that kind of time.. and I don't think it would look "replica"! Hope that it make sense 🤘🏻

**Comment by steverae68** [comment]
yeah absolute sense, mt second display is a 50" Pioneer plasma but my iMac is reporting it as a 23" 👎 

i think its an issue with the DisplayPort adapter I've 'borrowed' from work it aint DisplayPort 2.0 compatible, only DisplayPort 1.2 sp might not understand my thunderbolt port - i'll close this issue
