### ISSUE TITLE
Can't launch items from favorites shelf

### ISSUE THREAD

**Issue by scrolling101** [fastcolors/skin.sio2#38]
Can't launch items favorites from the shelf.

**Comment by fastcolors** [comment]
that's a kodi issue, will see if I can make it work with a script, but unless it's one I already use, I'm not incline in adding one more dependency just for favourites...

the issue is KODI has the node favourites://  and it fills the list... but has no link to clickable actions

better said the actions are "strings" and cannot be read by kodi (unless you're on fav page)

**Comment by scrolling101** [comment]
If it's a KODI issue then I would leave it as is.
