### ISSUE TITLE
Add blurry background to loading screen

### ISSUE THREAD

**Issue by badrabbit** [fastcolors/skin.sio2#45]
It would be nice if you could add the blurry background when the spinning loading wheel appears.
![visual-design-templates-loading](https://cloud.githubusercontent.com/assets/78358/21937342/5a74a8e6-d9b7-11e6-94e5-7db088179f5a.png)

I guess you'd need to implement the [color box-imageblur](http://forum.kodi.tv/showthread.php?tid=303846&pid=2499612#pid2499612) to use the current background as a blurred image.

Additionally it would be great if you could also change the text from "Loading..." to the selected item like ATV 4 does it? Don't know if that's possible. Just an improvement suggestion :-)

**Comment by fastcolors** [comment]
I think unless blurring gets introduced by KODI devs at core level, I don't feel like adding one more dependancy for blurring, also because that works well on powerful machines, but stalls everything on less resourceful systems, so i'd need to add a lot of conditionals to make it work. As per the label ATM dialogbusy doesn't have any info passed, so I'd have to introduce a huge variable and still I'd miss most of the correct content, so far I didn't even code the "Loading..", just the spinning wheel. If after all is done a slim way to implement this is found, i'll work it. but not a priority right now.

cheers!

**Comment by badrabbit** [comment]
Got it ;-)
Maybe then you could at least add the default background (light/dark version) as an overlay behind the spinning wheel?

**Comment by fastcolors** [comment]
do you think I should make it slightly transparent or just cover the whole?

**Comment by badrabbit** [comment]
Maybe slightly transparent. I'm not sure what looks best.

**Comment by badrabbit** [comment]
Maybe nitpicking ;-) but:

The current spinning wheel isn't centered vertically:
![bildschirmfoto 2017-01-15 um 12 00 06](https://cloud.githubusercontent.com/assets/78358/21962041/b681f724-db1a-11e6-9fa0-6d8cff6b8d3c.png)

Probably that's because there's the space for the "loading"-label. In my opinion there doesn't need to be a label notifying me that it's loading. I already know that :-)

Also the appearance of the blurry background and the spinning wheel would need a slightly longer fade in animation, just like on ATV4.

**Comment by fastcolors** [comment]
should look better ;-) please test

**Comment by steverae68** [comment]
yep :)  all good

**Comment by fastcolors** [comment]
@badrabbit ? check and close if all good

**Comment by badrabbit** [comment]
Looks great! Thanks!
