### ISSUE TITLE
Add more options to TV shelf

### ISSUE THREAD

**Issue by badrabbit** [fastcolors/skin.sio2#47]
Right now the TV shelf only shows the episode thumbs. Due the poor resolution of the thumbs they look less than sexy when displayed that big on the shelf ;-)

Maybe you could add an option to use the TV show **poster or fanart** instead?

**Comment by fastcolors** [comment]
try

$INFO[ListItem.Art(fanart)]

i'll maybe pass the selection to fanart, and if you use this addon (gotta understand a little its logic ..) you get high quality thumbs!

looking good on my side.. dunno if it's final choice but so far a good workaround.

**Comment by badrabbit** [comment]
Tried **Artwork Beef**, but in my case it won't work as i'm using PKC ([PlexKodiConnect](https://github.com/croneter/PlexKodiConnect)).

**Comment by fastcolors** [comment]
it will show fanart in that case... which is high quality. Will see if anything better comes around.
I do believe that a preview of the episode is functionally better, but i agree that poor quality ruins the overall look...

I'm very conflicted ahahahahah.

i can't even help with the whole PKC thing since I don't use it and I'm not particularly fan of plex...
does it let you choose the metadata to add? I mean can you link an image to <fanart> at episodes level?

**Comment by steverae68** [comment]
On the subject of tv shows, as we've already discussed, would it be possible to add a switch to show either episode thumbs or show posters in square format / fan art thingy you've just mentioned

You no when you can go to the top of the tv shows shelf and select either recommended ;) recently added or random, could a toggle not be set to show the two view choices ?

**Comment by badrabbit** [comment]
I think the switch/option should be in skin settings and not directly on the shelf. You'd probably set this once and never change it that often.

**Comment by fastcolors** [comment]
definitely a skin settings, but you guys think the fanart change I just made isn't good? I don' really like the TVshow poster idea, since on shelf we are at EPISODE level, and I'd like to show difference between episodes of the same serie showing up at the simultaneously... already the fanart way doesn't completely satisfy me... but i feel it more apple-y than posters (at EPS level),
unless I change for instance randomepisodes into randomtvshows, recomendedepisodes>inprgresstvshows, recentlyaddedepisodes>somethingelseatshowlevel.. then i'd make sense to show poster.



will work on it!

**Comment by badrabbit** [comment]
For my part i'm totally OK with the fanart being displayed. The only thing that bothers me is that there's just space for two and a half episode/fanart thumbs instead of five in poster mode.

Another possible option would be to switch to square thumbs, like Apple displays it's TV Shows. But that would mean there's need for a square thumbs scraper just for that and i don't know if something like that even exists. Just a thought.

**Comment by steverae68** [comment]
Atv with the release of the new tv app has changed things a bit.  Old atv prior to 10.2 would show random or popular tv shows with a square icon much the same way movies does, but with the addition of the TV app, this now shows recommended (next episode) currently watching shows etc.

Maybe we rename the to shows icon TV and we add another one for tv shows :)

**Comment by steverae68** [comment]
Here is my setup now, first the original ATV screen (grabbed from apples website )
![screen shot 2017-01-15 at 21 07 55](https://cloud.githubusercontent.com/assets/17755581/21966227/94428b36-db67-11e6-9bb6-0af33ac03482.png)

Next my Kodi screen setup

![screen shot 2017-01-15 at 21 12 59](https://cloud.githubusercontent.com/assets/17755581/21966234/9f840e20-db67-11e6-829b-3b9d9cac4683.png)

What i've done here is replace the Icon and name of the original TV shows section and named it TV just like the real ATV.  Ive then created a new icon and pointed it at my plugin for Trending TV Shows (just like apple does.

However thinking about it, by default we already get a new TV Shows icon by default, D'oh!  why don't i just rename that instead of deleting it and creating my own.... but you get the idea :)

Not a bad comparison 

One thing (from this comparison) - Can we rename the Recommended section of the TV section to Up Next like the ATV ?, as this shows my Next Episodes to watch from my library which is synced by Trakt.

**Comment by steverae68** [comment]
In all honesty, the episode thumbs probably best match this layout..... also we need to move the text slightly lower above the shelf icon AND comparing the two dark mode screen shots, the top row banner needs to be a little darker....

don't know if it is possible to select a different layout type for each of the 5 top shelf icons but if so, then looking at my layout above, Movies should be poster, TV Shows should be Square and TV should remain as episode (especially in the Recommended view, which should be renamed 'Up Next')

This will give us an almost perfect clone of ATV (The ultimate goal of all these skins)

**Comment by fastcolors** [comment]
ok my problem with this is that i don't really see the point of having 2 home button pointing at the same thing, let me explain.

In AppletV new TV function (which i don't have since Italy pays Apple the same but gets less) , You have a link to all the "episodes" of the subscription or anything you have that are available, meanwhile tv shows icon points ar available iTunes show for rent, that you might not own in one of your subscriptions. But in kodi shelf shows the episodes, conveniently ordered in next to watch, or recent etc... while if you want the container of all these (namely the tv shows "root container" you can have it by clicking on the icon (which in my opinion is always less actions then 2 right 1 up)... so unless TV and TVshows point at 2 completely different items, I feel that it would be a useless mockup...
let alone square tvshow icon scraper... does that exist?

PS: if you replace default TVshows Icon, with another pointing at TVSHOWS>TITLES, you'll obtain the shelf to get populated with posters of your library tvshows...

hope that makes sense...

will think about it, and do some searching

**Comment by steverae68** [comment]
Ok..... I have two TV show settings, the TV app is the original TV Shows section which points to my library showing my currently watching TV shows, I track these via trakt to keep my various devices in sync.

I then use the TV Shows icon pointing to a video addon showing trending TV shows which i can look through and if i like one i can add it to my library.

So my TV icon is the original TV shows with a different icon, poniting to my library.  The new TV Shows icon is a custom icon pointing to 'trending tv shows' from one of my various video addons.

This is kind of like the Recommended TV shows icon, however, this uses the extendedinfo plugin which i've grown to hate :(

**Comment by steverae68** [comment]
Im happy with the config i have setup now, however, can we at least make the slight changes i recommended, lowering the Recommended text on shelf and chagning it to Up Next. 

Can we also have an option to choose between episode thumbnail and fanart ?

**Comment by fastcolors** [comment]
settings added, plz test ;-)

**Comment by steverae68** [comment]
Yep, that work :)

I noticed a little typo in the option to switch between episode and fan art thumbs, other than that, it's all good :)

Can you please include my TV logo and iTunes logos in as part of the skin ?
![tv](https://cloud.githubusercontent.com/assets/17755581/22027590/3ba7e0fa-dccc-11e6-93ea-c72071d8bb64.png)

Any chance to change the 'Recommended' text to 'Up Next' ?

**Comment by fastcolors** [comment]
itunes?

these should be added to the external addon for extra icons.
https://github.com/fastcolors/resource.images.sio2.icons

**Comment by steverae68** [comment]
I nt have rights to upload additional icons to the external addon
