### ISSUE TITLE
OSD - Seeking inidcator

### ISSUE THREAD

**Issue by badrabbit** [fastcolors/skin.sio2#53]
Is it possible to add an option to turn off the big "seeking time"?

![bildschirmfoto 2017-01-15 um 12 07 39](https://cloud.githubusercontent.com/assets/78358/22116176/fe93122a-de6f-11e6-8579-e99a2ee43b44.png)

I personally dislike that indicators in every skin/platform as i don't find them necessary at all.

**Comment by fastcolors** [comment]
I hear you, the only issue is with "progressive skip" or whatever is called.. so that if you keep pressing left or right, the amount of skipping increases proportionally, and without a visual feedback is hard to tell what are you doing...

other than that I'm also not partial to those numbers... I fear that removing it completely could raise some complaints though...

I'll add a settings but leave it on by default.

**Comment by fastcolors** [comment]
i'm loving it without hahahahahaha... tempted to remove it completely or reverse the setting....

**Comment by fastcolors** [comment]
is this working for you?

**Comment by badrabbit** [comment]
I like it that way! Simple and clean. But i also don't use the adaptive/progessive seeking feature.

Maybe you could additionally add current & end time and make it the same size as the current timecode. But i don't know if it looks good, maybe place it on the top?

But that's just a thought. Would be a nice bonus.
