### ISSUE TITLE
GUI update

### ISSUE THREAD

**Issue by steverae68** [fastcolors/skin.sio2#56]
Ive noticed when you have multiple rows of icons on screen and you have say the movies top shelf showing. When you scroll down to the next row down, the top shelf should still show what you were last looking at......

if you know what i mean.  

Also, i know this has been mentioned before but can we not have an option to display either posters or square icons on the top shelf for each top shelf item ?

**Comment by fastcolors** [comment]
I know what you mean, but that would introduce a.. mess.

let me explain:
in order to populate shelf, the panels and list all point to a single variable, that changes depending on the selected items, so let's say movie shelf is visible and populated with well..."movies shelf", then when you highlight "favourites" the container for movies shelf stays visible... but it gets populated with favourites, that serves very well the purpose of populating "new" items, since the container is always the same and visible, but for example for addons, the content changes.

that said (hope it made sanse) in order to keep shelf populated with the content of an item NOT currently selected...( i.e. movie shelf when Favourites is highlighted) it would be well... a mess.. since variables don't have a "fallback" system...
hence... very very complicated...

**Comment by steverae68** [comment]
gotcha ... thank you for changing the recommended to 'Up Next' BTW, looks like a perfect clone of ATV for em now.

One more thing.....

Is it possible to hide the plugin dialog boxes for example, say you use a plugin, lets say 'salts' and it goes away and looks for sources to watch something, can the dialog box that says, looking for sources etc etc be hidden or is that a plugin feature ?

**Comment by fastcolors** [comment]
I believe that's a plugin feature, calling for a dialog in kodi... not much I can do about that...
