### ISSUE TITLE
Custom shelf items?

### ISSUE THREAD

**Issue by badrabbit** [fastcolors/skin.sio2#68]
Is there a way to set custom shelf items?
With skin.shortcuts it's usually possible to setup custom widgets to be displayed when highlighting the menu item. But there's no option for that in your version?

Right now i'd like to replace the default Live-TV with directly opening the tv channels instead of the default popup-menu to choose from. But after i've created my new Live-TV item all channel shortcuts are gone and i'm not able to set them up again.

**Comment by fastcolors** [comment]
could you test the submenu branch? 

Unfortunately You'll have to reset skin to default, but the added menu items should start to keep "widgets" in a more universal manner.

Actually walking down this road seems like an awesome idea, since ideally all nodes could be made "universal", feel enough theory, give it a spin and let me know if this works.

**Comment by badrabbit** [comment]
Ahm... Can't find any changes in the SUBMENU branch.

Installed it and reset all skin settings. New items still show the already available edit items:

- Choose item for menu
- Set label
- Set thumbnail
- Change action
- Delete 

But no way to add/change widgets.
The only difference i could spot is that shelf items now flash (instead of smooth fade in) when browsing home screen.

**Comment by fastcolors** [comment]
this doesn't give the option for custom widgets, but if you " replace the default Live-TV with directly opening the tv channels " you should still see the populating channel shelf, as much as adding or replacing movies or tvshows should keep the shelf populating with sio2 default options

can You confirm?

as per the non smooth animation, i need to work on it, because now the list gets updated slower than it fades in... since it's now a widget and not a direct variable anymore... so now the skin calls the widget, which calls the line, which calls the variable which evaluates and pass infos back... slooooowly.

but i plan to act directly on the widgets to change the contents, and that should bring the smooth back... but so far I was speed coding for functionality, once that is done i'll fancy it up.

**Comment by badrabbit** [comment]
Confirmed! Tested with Live-TV, replaced default action with TV channels and shelf items stay as they were.

**Comment by fastcolors** [comment]
sweet!
