### ISSUE TITLE
TV show shelf 

### ISSUE THREAD

**Issue by scrolling101** [fastcolors/skin.sio2#78]
When navigating to the TV show shelf you get stuck there.

**Comment by steverae68** [comment]
I concur with scrollibg101, I've reverted back to older version.
I found that when you navigate up to tv shelf and then highlight the option at top to change display, you can't get back and have to terminate kodi to quit.

**Comment by fastcolors** [comment]
test latest build

**Comment by steverae68** [comment]
Still the same, as soon as you move to to shows shelf, the words tv shows at the top highlight and everything locks up.

Same happens if you move to the word Movies on the movies shelf

Both movies and tv shows shelf now items as square with no way to choose view :(

**Comment by fastcolors** [comment]
did you try resetting skin settings to default?

**Comment by steverae68** [comment]
d'oh!  - working now,  however, now the shelf shows square posters for both movies and tv shows and anything that is shown on shelf, is this a prelude to being able to select between poster and square view ?

**Comment by fastcolors** [comment]
mmm, it's not, On my side everything works as normal... not sure why you get everything in square format. :-(

**Comment by scrolling101** [comment]
Resetting skin settings to default worked for me.

**Comment by steverae68** [comment]
found out with the issue is..... I don't use the library for my main TV shows and Movie apps, I use an addon shortcut.  
The default shelf display uses squareshortcutscommon for it's display, referenced by 'General'  changing this to reference postershortcutscommon gets me what I need for my setup.

going to play more with the code to see if I can get exactly what I want working :)
